services:
  - type: web
    name: nemazing-rp
    runtime: python
    plan: free
    buildCommand: python3 -m venv .venv && .venv/bin/pip install --upgrade pip && .venv/bin/pip install -r requirements.txt
    startCommand: .venv/bin/python -u -m app.main
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: CHANNEL_USERNAME
        value: "@nemazing"
      - key: DATABASE_URL
        sync: false
